# Generated by Django 3.1.1 on 2020-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_auto_20200914_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
