# Generated by Django 3.1.1 on 2020-09-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='records',
        ),
    ]
