# Generated by Django 3.1.1 on 2020-09-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0008_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out of Delivery'), ('Delivered', 'Delivered')], max_length=100, null=True),
        ),
    ]
