# Generated by Django 3.1.1 on 2020-09-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
