# Generated by Django 3.1.1 on 2020-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0010_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slugCustomer',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='slugOrder',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slugOrderitem',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slugProduct',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
