# Generated by Django 3.1.1 on 2020-09-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0011_auto_20200919_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
