# Generated by Django 3.1.1 on 2020-09-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0015_auto_20200920_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
