# Generated by Django 3.1.1 on 2020-09-20 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0017_allmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmodels',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
