# Generated by Django 3.1.1 on 2020-09-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0018_allmodels_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allModels',
        ),
    ]
