# Generated by Django 3.1.1 on 2020-09-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0019_delete_allmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.shippingaddress'),
        ),
    ]
