# Generated by Django 3.1.1 on 2020-09-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0020_orderitem_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
