# Generated by Django 3.1.1 on 2020-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0021_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://via.placeholder.com/500x300/DCDCDC/FFF?text=Dharmie+Parfait', null=True, upload_to=''),
        ),
    ]
