# Generated by Django 3.1.1 on 2020-10-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0025_auto_20201002_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flutter',
            old_name='encryption_key',
            new_name='encryptionKey',
        ),
        migrations.RenameField(
            model_name='flutter',
            old_name='public_key',
            new_name='publicKey',
        ),
        migrations.RenameField(
            model_name='flutter',
            old_name='secret_key',
            new_name='secretKey',
        ),
    ]
