# Generated by Django 3.1.1 on 2020-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0026_auto_20201002_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Out For Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default=('Pending', 'Pending'), max_length=100, null=True),
        ),
    ]
